## tomcat端口号配置
server:
  port: 8884
  servlet:
    context-path: /       #项目访问路径
spring:
  dubbo:
    appname: consumer-test        #dubbo应用名称
    registry: zookeeper://47.108.70.12:2181   #zookeeper注册中心
    protocol: dubbo     #dubbo协议